/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/calendar/event_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CalendarService_listEventTypes"];
        put?: never;
        post: operations["CalendarService_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/event_types/{eventTypeId}/available_slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CalendarService_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/scheduled_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CalendarService_listScheduledEvents"];
        put?: never;
        post: operations["CalendarService_createScheduledEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/scheduled_events/{scheduledEventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CalendarService_getScheduledEventById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Calendar: {
            ownerName: string;
            ownerEmail: string;
            /** Format: time */
            startOfTheDayHour: string;
            /** Format: time */
            endOfTheDayHour: string;
            breaks: components["schemas"]["TimeSlot"][];
            workingDays: components["schemas"]["DayOfWeek"][];
        };
        CreateEventType: {
            eventTypeName: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        CreateScheduledEvent: {
            eventTypeId: string;
            /** Format: date */
            date: string;
            /** Format: time */
            time: string;
            subject: string;
            notes: string;
            guestName: string;
            guestEmail: string;
            guestTimezone: string;
        };
        /** @enum {string} */
        DayOfWeek: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
        Error: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        EventType: {
            readonly eventTypeId: string;
            eventTypeName: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        ScheduledEvent: {
            readonly scheduledEventId: string;
            eventTypeId: string;
            /** Format: date-time */
            utcDateStart: string;
            /** Format: int32 */
            durationMinutes: number;
            subject: string;
            notes: string;
            guestName: string;
            guestEmail: string;
            guestTimezone: string;
        };
        TimeSlot: {
            /** Format: time */
            timeStart: string;
            /** Format: int32 */
            duration: number;
        };
        TimeSlotsOfTheDay: {
            /** Format: date */
            date: string;
            timeSlots: components["schemas"]["TimeSlot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CalendarService_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "eventTypeId": "et_intro_30",
                     *         "eventTypeName": "Intro Call",
                     *         "description": "A short get-to-know-you chat. Great for first contact.",
                     *         "durationMinutes": 30
                     *       },
                     *       {
                     *         "eventTypeId": "et_strategy_60",
                     *         "eventTypeName": "Strategy Session",
                     *         "description": "Deep-dive working session for project planning and roadmapping.",
                     *         "durationMinutes": 60
                     *       },
                     *       {
                     *         "eventTypeId": "et_quick_15",
                     *         "eventTypeName": "Quick Sync",
                     *         "description": "Fast 15-minute check-in for status updates or quick questions.",
                     *         "durationMinutes": 15
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CalendarService_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventType"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CalendarService_listAvailableSlots: {
        parameters: {
            query: {
                clientTimeZone: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "date": "2026-05-01",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "09:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "16:00:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-04",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "09:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:30:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-05",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "16:30:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-06",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-07",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "09:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "16:00:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-08",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:30:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-11",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "11:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "15:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "16:00:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       },
                     *       {
                     *         "date": "2026-05-12",
                     *         "timeSlots": [
                     *           {
                     *             "timeStart": "09:30:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "10:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "13:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:00:00",
                     *             "duration": 30
                     *           },
                     *           {
                     *             "timeStart": "14:30:00",
                     *             "duration": 30
                     *           }
                     *         ]
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["TimeSlotsOfTheDay"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CalendarService_listScheduledEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledEvent"][];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CalendarService_createScheduledEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduledEvent"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledEvent"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CalendarService_getScheduledEventById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduledEventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledEvent"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
